config/routes.rb
SchoolInfoWebsite::Application.routes.draw do

  devise_for :admins

  root 'static_page#home'

  namespace :admins do
    resources :pages
  end

  get '/home' => 'static_page#home', as: 'home'
  get '/academics' => 'static_page#academics', as: 'academics'
  get '/activities' => 'static_page#activities', as: 'activities'
  get '/policies' => 'static_page#policies', as: 'policies'
  get '/events' => 'static_page#events', as: 'events'
  get '/contactus' => 'static_page#contactus', as: 'contactus'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/admins.rb
module Admins
  def self.table_name_prefix
    'admins_'
  end
end

app/models/admins/page.rb
class Admins::Page < ActiveRecord::Base
end

app/controllers/admins/pages_controller.rb
class Admins::PagesController < ApplicationController
  before_action :set_admins_page, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  # GET /admins/pages
  # GET /admins/pages.json
  def index
    @admins_pages = Admins::Page.all
  end

  # GET /admins/pages/1
  # GET /admins/pages/1.json
  def show
  end

  # GET /admins/pages/new
  def new
    @admins_page = Admins::Page.new
  end

  # GET /admins/pages/1/edit
  def edit
  end

  # POST /admins/pages
  # POST /admins/pages.json
  def create
    @admins_page = Admins::Page.new(admins_page_params)

    respond_to do |format|
      if @admins_page.save
        format.html { redirect_to @admins_page, notice: 'Page was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admins_page }
      else
        format.html { render action: 'new' }
        format.json { render json: @admins_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admins/pages/1
  # PATCH/PUT /admins/pages/1.json
  def update
    respond_to do |format|
      if @admins_page.update(admins_page_params)
        format.html { redirect_to @admins_page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admins_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/pages/1
  # DELETE /admins/pages/1.json
  def destroy
    @admins_page.destroy
    respond_to do |format|
      format.html { redirect_to admins_pages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admins_page
      @admins_page = Admins::Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admins_page_params
      params[:admins_page]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController

	def home

	end

	def academics

	end

	def activities

	end

	def policies

	end

	def events

	end

	def contactus

	end
end

app/helpers/admins/pages_helper.rb
module Admins::PagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def login_or_logout_link
		if admin_signed_in?
			link_to "Log Out", destroy_admin_session_path, method: :delete
		else
			link_to "Log In", new_admin_session_path
		end
	end

	def admin_link
		if admin_signed_in?
			link_to "Modify Website Content", admins_pages_path, method: :get
		end
	end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/admins/pages/_form.html.erb
<%= form_for(@admins_page) do |f| %>
  <% if @admins_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admins_page.errors.count, "error") %> prohibited this admins_page from being saved:</h2>

      <ul>
      <% @admins_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/pages/edit.html.erb
<h1>Editing admins_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @admins_page %> |
<%= link_to 'Back', admins_pages_path %>

app/views/admins/pages/index.html.erb
<h1>Listing admins_pages</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @admins_pages.each do |admins_page| %>
      <tr>
        <td><%= link_to 'Show', admins_page %></td>
        <td><%= link_to 'Edit', edit_admins_page_path(admins_page) %></td>
        <td><%= link_to 'Destroy', admins_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_admins_page_path %>

app/views/admins/pages/new.html.erb
<h1>New admins_page</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_pages_path %>

app/views/admins/pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admins_page_path(@admins_page) %> |
<%= link_to 'Back', admins_pages_path %>

app/views/layouts/_header.html.erb
<div>
	<div class="nav">
		<ul class="nav nav-tabs">
			<li><%= link_to "Home", home_path %></li>
			<li><%= link_to "Academics", academics_path %></li>
			<li><%= link_to "Activities", activities_path %></li>
			<li><%= link_to "Policies", policies_path %></li>
			<li><%= link_to "Events", events_path %></li>
			<li><%= link_to "ContactUs", contactus_path %></li>
			<li><%= admin_link %></li>	
			<li><%= login_or_logout_link %></li>
		</ul>
	</div>
</div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>SchoolInfoWebsite</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<%= render 'layouts/header'%>
	</div>
	<div class="container">
		<%= yield %>
	</div>
	<div class="container">
		<%= render 'layouts/footer'%>
	</div>
</body>
</html>

app/views/static_page/home.html.erb
hhome